description = 'Documentation of selfhosted homelab'

author = 'Nig3l'
authorURL = 'https://ni-g-3l.github.io/Ni-g-3l/'

currentYear = 2023

githubURL = 'https://github.com/Ni-g-3l'
youtubeURL = ''
twitterURL = ''
facebookURL = ''

githubRepo = 'Ni-g-3l/homelab'
githubSponsorURL = ''
buyMeACoffeeURL = ''

[algolia]
[algolia.en]
container = ''
appId = ''
indexName = ''
apiKey = ''

[[githubRepos]]
name = 'Homelab'
repo = 'selfhosted-homelab/homelab'
icon = "<i class='icon icon-home'></i>"
description = 'The repository of the homelab.'

[[githubRepos]]
name = 'Documentation'
repo = 'selfhosted-homelab/selfhosted-homelab.github.io'
icon = "<i class='icon icon-book'></i>"
description = 'The repository of the documentation.'
